#!/usr/bin/env bash

track=typescript
exercise=$1

script_dir=$(dirname "$0")

export _exercism_solution_file=${exercise}.ts
export _exercism_test_file=${exercise}.test.ts
export _exercism_run_tests_command="corepack yarn test"

export _exercism_run_after_download="corepack yarn install"

bash "$script_dir/exercism-template" $track "$exercise"

