#!/usr/bin/env bash

track=python
exercise=$1

script_dir=$(dirname "$0")

export _exercism_solution_file=${exercise//-/_}.py
export _exercism_test_file=${exercise//-/_}_test.py
export _exercism_run_tests_command="pytest --color yes"

bash "$script_dir/exercism-template" $track "$exercise"

