#!/usr/bin/env bash

track=raku
exercise=$1

script_dir=$(dirname "$0")

export _exercism_solution_file="lib/*"
export _exercism_test_file="t/*"
export _exercism_run_tests_command="prove6"

bash "$script_dir/exercism-template" $track "$exercise"

