#!/usr/bin/env bash

track=kotlin
exercise=$1

script_dir=$(dirname "$0")

export _exercism_solution_file='src/main/kotlin/*.kt'
export _exercism_test_file='src/test/kotlin/*.kt'
export _exercism_run_tests_command="sh gradlew test"

bash "$script_dir/exercism-template" $track "$exercise"


