#!/usr/bin/env bash

track=crystal
exercise=$1

script_dir=$(dirname "$0")

export _exercism_solution_file="src/*"
export _exercism_test_file="spec/*"
export _exercism_run_tests_command="crystal spec"

bash "$script_dir/exercism-template" $track "$exercise"

