#!/usr/bin/env bash

track=ruby
exercise=$1

script_dir=$(dirname "$0")

export _exercism_solution_file=${exercise//-/_}.rb
export _exercism_test_file=${exercise//-/_}_test.rb
export _exercism_run_tests_command="ruby ${_exercism_test_file}"

bash "$script_dir/exercism-template" $track "$exercise"


