#!/usr/bin/env bash

track=vbnet
exercise=$1

script_dir=$(dirname "$0")

export _exercism_solution_file='$(find . -name "*.vb" -and -not -name "*Tests.vb")'
export _exercism_test_file='$(find . -name "*Tests.vb")'
export _exercism_run_tests_command="dotnet test"

bash "$script_dir/exercism-template" $track "$exercise"

